<?php
return array (
  'mxprocms' => 
  array (
    's1' => 
    array (
      'logo1' => 'upload/mxprocms/20230124-1/a43f6fed41e174f27a9e3744f874f6f2.png',
      'logo2' => 'upload/mxprocms/20230124-1/5293313a153c0ed2d4178b778633d43d.png',
      'ico' => 'mxtheme/images/favicon.png',
      'pic' => 'mxtheme/images/load.gif',
      'userbg' => 'mxtheme/images/userbg.jpg',
      'searchwd' => '搜索电影、电视剧、综艺、动漫',
      'sm' => '本站所有内容均来自互联网分享站点所提供的公开引用资源，未提供资源上传、存储服务，如有侵权请联系：saboranmin@gmail.com',
    ),
    's2' => 
    array (
      'theme' => 'white',
      'searchtips' => '1',
      'douban' => '1',
      'dbfktext' => '底部反馈',
      'dbfkurl' => 'https://www.banyungou.net/',
      'qqquntext' => 'QQ交流群',
      'qqqunurl' => 'https://www.banyungou.net/',
      'telegramtext' => 'Telegram群',
      'telegramurl' => 'https://www.banyungou.net/',
      'daohangid' => 'parent',
      'iconmr' => 'icon-jl-o',
      'num1' => '1',
      'icon1' => 'icon-dy-o',
      'num2' => '2',
      'icon2' => 'icon-tv-o',
      'num3' => '3',
      'icon3' => 'icon-zy-o',
      'num4' => '4',
      'icon4' => 'icon-dm-o',
      'num5' => '',
      'icon5' => '',
      'num6' => '',
      'icon6' => '',
      'num7' => '',
      'icon7' => '',
      'diy1' => '0',
      'diy1name' => '',
      'diy1url' => '',
      'diy1icon' => 'icon-diy',
      'diy2' => '0',
      'diy2name' => '',
      'diy2url' => '',
      'diy2icon' => 'icon-diy',
      'todaynew' => '1',
      'diyheaddm' => '',
      'diy2headdm' => '',
      'appname' => 'APP',
      'appurl' => '/index.php/label/down.html',
      'appicon' => 'icon-phone-o',
      'zongkg' => '1',
      'up' => '1',
    ),
    's4' => 
    array (
      'apptxt' => 'Mxone Pro网站APP',
      'appentxt' => '海量高清影片、更佳观影体验，尽在Mxone Pro APP',
      'android' => '0',
      'androidtxt' => 'Android版',
      'androidurl' => 'https://www.banyungou.net/',
      'androidicon' => 'icon-android',
      'ios' => '0',
      'iostxt' => 'ios版',
      'iosurl' => 'https://www.banyungou.net/',
      'iosicon' => 'icon-apple',
      'win' => '0',
      'wintxt' => '客户端版',
      'winurl' => 'https://www.banyungou.net/',
      'winicon' => 'icon-windows',
      'appewm' => 'mxtheme/images/ewm.png',
      'liketext' => '相关推荐',
      'likeyear' => '2023,2022',
      'likenum' => '16',
      'qrcodetips' => '被部分浏览器误屏蔽，为保证正常访问，推荐使用<strong>Chrome</strong>、<strong>Edge</strong>、<strong>Safari</strong>等浏览器。 ',
      'copyrighttxt' => '应版权方要求该资源已下架',
      'type' => '1',
      'typelevel' => '0',
      'typeby' => 'time',
      'typeyear' => '2023,2022',
      'typenum' => '16',
      'type1' => '1',
      'typetext' => '新片上线',
      'typetexteg' => 'NEW FILM ONLINE',
      'typeby1' => 'time',
      'typeyear1' => '2023,2022',
      'typenum1' => '16',
      'typestart' => '1',
      'type2' => '1',
      'typetext1' => '排行榜',
      'typetexteg1' => 'RANKING',
      'typeyear2' => '2023,2022',
      'typenum2' => '16',
      'type3' => '1',
      'typetext2' => '最近更新',
      'typetexteg2' => 'LATEST UPDATE',
      'typeby3' => 'time',
      'typeyear3' => '2023,2022',
      'typenum3' => '16',
      'showclass' => '1',
      'showjq' => '1',
      'showarea' => '1',
      'showyear' => '1',
      'showlang' => '1',
      'showzm' => '1',
      'showby' => '1',
      'newtext' => '今日更新',
      'newby' => 'time',
      'neworder' => 'desc',
      'newyear' => '',
      'newnum' => '48',
      'newtext1' => '新片上线',
      'newby1' => 'time',
      'neworder1' => 'desc',
      'newyear1' => '2022',
      'newnum1' => '48',
      'hottext' => '最近热门',
      'hotby' => 'hits',
      'hotorder' => 'desc',
      'hotyear' => '',
      'hotnum' => '48',
      'hottext1' => '近期热门',
      'hotby1' => 'hits',
      'hotorder1' => 'desc',
      'hotyear1' => '2022',
      'hotnum1' => '48',
    ),
    's3' => 
    array (
      'slide' => '1',
      'slidebill' => '1',
      'slidetj' => 'all',
      'slidenum' => '10',
      'slideby' => 'time',
      'slideorder' => 'desc',
      'slidefb' => '1',
      'indexweektext' => '追剧周表',
      'indexweeknum' => '10',
      'indexhotpic' => '1',
      'indexhottext' => '正在热映',
      'indexhottj' => '1',
      'indexhotnum' => '16',
      'indexlist' => '1',
      'indexlistid' => 'parent',
      'indexlistnum1' => '16',
      'indexlistby1' => 'time',
      'indexlistyear1' => '2022',
      'indexlistorder1' => 'desc',
      'indextop' => '1',
      'indextopid' => 'parent',
      'indextoptext' => '热榜',
      'indextopeg' => 'RANKING',
      'indextopnum' => '10',
      'indextopby' => 'hits',
      'indextopyear' => '2022',
      'indextoporder' => 'desc',
      'indexlinknum' => '99',
    ),
    's5' => 
    array (
      'noticetext' => '公告内容',
      'noticecontent' => '<strong>欢迎使用Mxone Pro模板，本模板由搬运狗(www.banyungou.net)制作，谢谢支持！</strong><br/>1.化繁为简<br/>2.全新框架全新UI<br/>3.去除多余繁杂的页面和功能给你一款简约清新的模板<br/>更多功能请慢慢体验！！！',
      'shier' => '0',
      'ctrl' => '0',
      'right' => '0',
      'mode' => '0',
      'pbtips' => '你知道的太多了',
      'tbdmtips' => '',
      'dbdmtips' => '<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?660e5fa19554aa062fc9009d26e3bb88";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
',
      'stylecss' => '',
    ),
    's6' => 
    array (
      'adsindexdm' => '',
      'adsindexlistdm' => '',
      'adsdetdm' => '',
      'adsplaydm' => '',
      'adsplaybfqdm' => '',
      'adssearchdm' => '',
      'adsscreendm' => '',
    ),
  ),
);