<?php
return array (
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'sort' => '907',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva-H5播放器',
    'des' => 'videojj.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '906',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'ps' => '0',
    'parse' => '',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'sort' => '904',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'sort' => '903',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'flv' => 
  array (
    'status' => '1',
    'from' => 'flv',
    'show' => 'Flv文件',
    'des' => 'flv',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '902',
    'tip' => '无需安装任何插件	',
    'id' => 'flv',
  ),
  'tpiframe' => 
  array (
    'status' => 1,
    'from' => 'tpiframe',
    'show' => 'tpiframe',
    'des' => '',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => 102,
    'tip' => '',
    'id' => 'tpiframe',
  ),
  'tpm3u8' => 
  array (
    'status' => 1,
    'from' => 'tpm3u8',
    'show' => 'tpm3u8',
    'des' => '',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => 102,
    'tip' => '',
    'id' => 'tpm3u8',
  ),
  'tkyun' => 
  array (
    'status' => '1',
    'from' => 'tkyun',
    'show' => '天空云',
    'des' => '在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '991',
    'tip' => '',
    'id' => 'tkyun',
  ),
  'tkm3u8' => 
  array (
    'status' => '1',
    'from' => 'tkm3u8',
    'show' => '天空M3U8',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.huishij.com/yun/?url=',
    'sort' => '990',
    'tip' => '',
    'id' => 'tkm3u8',
  ),
  'kcyun' => 
  array (
    'status' => '1',
    'from' => 'kcyun',
    'show' => '快车云',
    'des' => 'kcyun',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '9999999',
    'tip' => '无需安装任何插件	',
    'id' => 'kcyun',
  ),
  'kcm3u8' => 
  array (
    'status' => '1',
    'from' => 'kcm3u8',
    'show' => '快车资源',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '99999',
    'tip' => '',
    'id' => 'kcm3u8',
  ),
  '1080zyk' => 
  array (
    'status' => '1',
    'from' => '1080zyk',
    'show' => '1080zyk',
    'des' => 'http://1080zyku.com/',
    'ps' => '1',
    'parse' => 'https://vip.zykbf.com/?url=',
    'sort' => '99',
    'tip' => '在线播放,无需安装播放器',
    'id' => '1080zyk',
  ),
  'zykyun' => 
  array (
    'status' => '1',
    'from' => 'zykyun',
    'show' => 'zykyun',
    'des' => 'http://1080zyku.com/',
    'ps' => '0',
    'parse' => '',
    'sort' => '99',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'zykyun',
  ),
  'dbm3u8' => 
  array (
    'status' => '1',
    'from' => 'dbm3u8',
    'show' => 'dbm3u8',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.jxbdzyw.com/m3u8/?url=',
    'sort' => '100',
    'tip' => '',
    'id' => 'dbm3u8',
  ),
  'dbyun' => 
  array (
    'status' => '1',
    'from' => 'dbyun',
    'show' => 'dbyun',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '100',
    'tip' => '',
    'id' => 'dbyun',
  ),
);