<?php
return array (
  'ukyun' => 
  array (
    'status' => '1',
    'from' => 'ukyun',
    'show' => 'ukyun',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '100',
    'tip' => '',
    'id' => 'ukyun',
  ),
  '1080zyk' => 
  array (
    'status' => '1',
    'from' => '1080zyk',
    'show' => '1080zyk',
    'des' => 'http://1080zyku.com/',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://vip.zykbf.com/?url=',
    'sort' => '99',
    'tip' => '在线播放,无需安装播放器',
    'id' => '1080zyk',
  ),
  'hnyun' => 
  array (
    'status' => '1',
    'from' => 'hnyun',
    'show' => 'hnyun',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '23',
    'tip' => '',
    'id' => 'hnyun',
  ),
  'hnm3u8' => 
  array (
    'status' => '1',
    'from' => 'hnm3u8',
    'show' => 'hnm3u8',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '22',
    'tip' => '',
    'id' => 'hnm3u8',
  ),
  'ukm3u8' => 
  array (
    'status' => '0',
    'from' => 'ukm3u8',
    'show' => 'ukm3u8',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://api.ukubf.com/m3u8/?url=',
    'sort' => '21',
    'tip' => '',
    'id' => 'ukm3u8',
  ),
  'wjm3u8' => 
  array (
    'status' => '0',
    'from' => 'wjm3u8',
    'show' => '无尽',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.wujinkk.com/dplayer/?url=',
    'sort' => '19',
    'tip' => '',
    'id' => 'wjm3u8',
  ),
  'wjyun' => 
  array (
    'status' => '0',
    'from' => 'wjyun',
    'show' => '无尽云',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => '',
    'sort' => '18',
    'tip' => '呃呃呃',
  ),
  'zykyun' => 
  array (
    'status' => '1',
    'from' => 'zykyun',
    'show' => 'zykyun',
    'des' => 'http://1080zyku.com/',
    'ps' => '0',
    'parse' => '',
    'sort' => '17',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'zykyun',
  ),
  'dbyun' => 
  array (
    'status' => '0',
    'from' => 'dbyun',
    'show' => 'dbyun',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '15',
    'tip' => '',
    'id' => 'dbyun',
  ),
  'dbm3u8' => 
  array (
    'status' => '0',
    'from' => 'dbm3u8',
    'show' => 'dbm3u8',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.jxbdzyw.com/m3u8/?url=',
    'sort' => '14',
    'tip' => '',
    'id' => 'dbm3u8',
  ),
  'tpm3u8' => 
  array (
    'status' => 1,
    'from' => 'tpm3u8',
    'show' => 'tpm3u8',
    'des' => '',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => 13,
    'tip' => '',
    'id' => 'tpm3u8',
  ),
  'tpiframe' => 
  array (
    'status' => 1,
    'from' => 'tpiframe',
    'show' => 'tpiframe',
    'des' => '',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => 12,
    'tip' => '',
    'id' => 'tpiframe',
  ),
  'flv' => 
  array (
    'status' => '1',
    'from' => 'flv',
    'show' => 'Flv文件',
    'des' => 'flv',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '11',
    'tip' => '无需安装任何插件	',
    'id' => 'flv',
  ),
  'swf' => 
  array (
    'status' => '1',
    'sort' => '10',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'link' => 
  array (
    'status' => '1',
    'sort' => '9',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'ps' => '0',
    'parse' => '',
    'sort' => '8',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva-H5播放器',
    'des' => 'videojj.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '7',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'sort' => '6',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '5',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'tkm3u8' => 
  array (
    'status' => '1',
    'from' => 'tkm3u8',
    'show' => '天空M3U8',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.huishij.com/yun/?url=',
    'sort' => '4',
    'tip' => '',
    'id' => 'tkm3u8',
  ),
  'tkyun' => 
  array (
    'status' => '1',
    'from' => 'tkyun',
    'show' => '天空云',
    'des' => '在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '3',
    'tip' => '',
    'id' => 'tkyun',
  ),
  'kcm3u8' => 
  array (
    'status' => '1',
    'from' => 'kcm3u8',
    'show' => '快车资源',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '2',
    'tip' => '',
    'id' => 'kcm3u8',
  ),
  'kcyun' => 
  array (
    'status' => '1',
    'from' => 'kcyun',
    'show' => '快车云',
    'des' => 'kcyun',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1',
    'tip' => '无需安装任何插件	',
    'id' => 'kcyun',
  ),
  'ptyun' => 
  array (
    'status' => '1',
    'from' => 'ptyun',
    'show' => 'ptyun',
    'des' => 'ptyun',
    'target' => '_self',
    'ps' => '1',
    'parse' => '//jiexi.xxzy.org/?url=',
    'sort' => '1',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'ptyun',
  ),
  'wolong' => 
  array (
    'status' => '0',
    'from' => 'wolong',
    'show' => 'wolong',
    'des' => '卧龙资源',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.wolongzywcdn.com:65/m3u8.php?url=',
    'sort' => '1',
    'tip' => '',
    'id' => 'wolong',
  ),
);